/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SSTT_Interfaces;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Hashtable;
import java.util.Scanner;

/**
 *
 * @author TOSHIBA
 */
public class CreatePhone extends javax.swing.JFrame {

    /**
     * Creates new form CreatePhone
     */
    public CreatePhone() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        gramText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gramText.setFont(new java.awt.Font("Iskoola Pota", 0, 11)); // NOI18N
        gramText.setText("<word>=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(gramText))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(gramText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        Hashtable<String,String> sinhalaPhones=new Hashtable<String,String>();
        
//        sinhalaPhones.put("ම", "M AH");
//        sinhalaPhones.put("ග", "G");
//        sinhalaPhones.put("ේ", "EH");
//        sinhalaPhones.put("", null)
        try {
            File phoneFile=new File("/Users/janitha/Documents/kdu/semester 4/Group project in Software Engineering/final/Sinhala Speech To Text/SinhalaSTT1.0/src/SSTT_Interfaces/phonemes.txt");
            Scanner sc=new Scanner(phoneFile,"Unicode");
            while(sc.hasNextLine()){
                String line=sc.nextLine();
                sinhalaPhones.put(line.substring(0,1), line.substring(2));
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            String lineWord=null;
            File wordFile=new File("/Users/janitha/Documents/kdu/semester 4/Group project in Software Engineering/final/Sinhala Speech To Text/SinhalaSTT1.0/src/SSTT_Interfaces/sinwords.txt");
            File dictFile  =new File("/Users/janitha/Documents/kdu/semester 4/Group project in Software Engineering/final/Sinhala Speech To Text/SinhalaSTT1.0/src/SSTT_Interfaces/gramFile.txt");
            if(!dictFile.exists()){
                dictFile.createNewFile();
            }
            FileWriter dictFileWriter=new FileWriter(dictFile);
            BufferedWriter dictBuffer=new BufferedWriter(dictFileWriter);
            
            Scanner sc2=new Scanner(wordFile);
            String phone=null;
            for(int j=0;j<20;j++){
                lineWord=sc2.next();
                String arr[]=lineWord.split("");
                textArea.append(lineWord+"                                      ");
                gramText.setText(gramText.getText()+lineWord+"|");
                for(int i=0;i<arr.length;i++){
                    phone=sinhalaPhones.get(arr[i]);
                    if(phone==null){
                        continue;
                    }
                    
                    textArea.append("   "+phone);
                 }
                textArea.append("\n");
            }
            
            dictBuffer.write(textArea.getText());
            dictBuffer.close();
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePhone().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gramText;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}


